package swt_projektplaner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultListModel;
/**
 *
 * @author Jan Beuster
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
        
    }
    public static Datenbank db = new Datenbank();
    public static ProjektVerwaltung pv = new ProjektVerwaltung();
    public static MitarbeiterVerwaltung bv = new MitarbeiterVerwaltung();
    public static ArbeitspaketVerwaltung av = new ArbeitspaketVerwaltung();
    public static KleineVerwaltung kv = new KleineVerwaltung();
    public static AuftraggeberVerwaltung agv = new AuftraggeberVerwaltung();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonGroupRangAuswaehlen = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        StartseiteEinloggen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EinloggenBenutzername = new javax.swing.JTextField();
        EinloggenPasswort = new javax.swing.JPasswordField();
        ButtonStartseiteEinloggen = new javax.swing.JButton();
        Menu = new javax.swing.JPanel();
        ButtonMenuProjektAnlegen = new javax.swing.JButton();
        ButtonMenuBenutzerAnlegen = new javax.swing.JButton();
        ButtonMenuProjekteAnsehen = new javax.swing.JButton();
        ButtonMenuArbeitspaketeAnsehen = new javax.swing.JButton();
        ProjektAnlegen = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        LabelBeschreibung = new javax.swing.JLabel();
        LabelDeadline = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        ButtonProjektAnlegen = new javax.swing.JButton();
        TitelProjektAnlegen = new javax.swing.JLabel();
        ComboBoxTag = new javax.swing.JComboBox<>();
        ComboBoxMonat = new javax.swing.JComboBox<>();
        ComboBoxJahr = new javax.swing.JComboBox<>();
        ButtonBackProjektAnlegen = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextAreaBeschreibung = new javax.swing.JTextArea();
        ArbeitspaketeAnsehen = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ListArbeitspaketeAnsehen = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RadioButtonArbeitspaketFertig = new javax.swing.JRadioButton();
        ButtonArbeitspaketeAnsehenZurück = new javax.swing.JButton();
        ProjekteAnsehen = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListProjekteAnsehen = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        ButtonBackProjekteAnsehen = new javax.swing.JButton();
        ButtonProjektBearbeiten = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaProjektBeschreibung = new javax.swing.JTextArea();
        ProjektBearbeiten = new javax.swing.JPanel();
        LabelProjekteAnsehenSub = new javax.swing.JLabel();
        LabelProjektName = new javax.swing.JLabel();
        LabelProjektBeschreibung = new javax.swing.JLabel();
        LabelProjektDeadline = new javax.swing.JLabel();
        TextFieldProjektName = new javax.swing.JTextField();
        TextFieldProjektBeschreibung = new javax.swing.JTextField();
        LabelKommentar = new javax.swing.JLabel();
        TextFieldKommentar = new javax.swing.JTextField();
        TextFieldNotiz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonArbeitspaketBearbeiten = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListArbeitspakete = new javax.swing.JList<>();
        ButtonProjektBearbeitenZurück = new javax.swing.JButton();
        ButtonProjektAendern = new javax.swing.JButton();
        ComboBoxProjektBearbeitenTag = new javax.swing.JComboBox<>();
        ComboBoxProjektBearbeitenMonat = new javax.swing.JComboBox<>();
        ComboBoxProjektBearbeitenJahr = new javax.swing.JComboBox<>();
        ArbeitspaketAnlegen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ButtonArbeitspaketAnlegenZurück = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextFieldAName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        ButtonArbeitspaketAnlegen = new javax.swing.JButton();
        ComboBoxATag = new javax.swing.JComboBox<>();
        ComboBoxAMonat = new javax.swing.JComboBox<>();
        ComboBoxAJahr = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextAriaBeschreibung = new javax.swing.JTextArea();
        BenutzerAnlegen = new javax.swing.JPanel();
        TitelBenutzerAnlegen = new javax.swing.JLabel();
        LabelVorname = new javax.swing.JLabel();
        LabelNachname = new javax.swing.JLabel();
        LabelPasswort = new javax.swing.JLabel();
        LabelRang = new javax.swing.JLabel();
        TextFieldVorname = new javax.swing.JTextField();
        TextFieldNachname = new javax.swing.JTextField();
        TextFieldPasswort = new javax.swing.JTextField();
        RadioButtonStandardBenutzer = new javax.swing.JRadioButton();
        RadioButtonAdministrator = new javax.swing.JRadioButton();
        ButtonBenutzerAnlegen = new javax.swing.JButton();
        ButtonBenutzerprofilAnlegenZurück = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TextFieldBenutzername = new javax.swing.JTextField();
        MitarbeiterHinzufuegen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeMitarbeiterHinzufuegen = new javax.swing.JList<>();
        ButtonBackMenu = new javax.swing.JButton();
        ButtonWeiterArbeitspakete = new javax.swing.JButton();
        ButtonMitarbeiterHinzufügen = new javax.swing.JButton();
        ArbeitspaketBearbeiten = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TextFieldANameBearbeiten = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextAreaABeschreibungBearbeiten = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        ComboBoxATagBearbeiten = new javax.swing.JComboBox<>();
        ComboBoxAMonatBearbeiten = new javax.swing.JComboBox<>();
        ComboBoxAJahrBearbeiten = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        CheckBoxArbeitspaketFertig = new javax.swing.JCheckBox();
        ButtonArbeitspaketBearbeitenÄndern = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel12.setText("Benutzername");

        jLabel13.setText("Passwort");

        EinloggenPasswort.setText("jPasswordField1");

        ButtonStartseiteEinloggen.setText("Einloggen");
        ButtonStartseiteEinloggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartseiteEinloggenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartseiteEinloggenLayout = new javax.swing.GroupLayout(StartseiteEinloggen);
        StartseiteEinloggen.setLayout(StartseiteEinloggenLayout);
        StartseiteEinloggenLayout.setHorizontalGroup(
            StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartseiteEinloggenLayout.createSequentialGroup()
                .addGroup(StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartseiteEinloggenLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(49, 49, 49)
                        .addGroup(StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EinloggenBenutzername, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(EinloggenPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(StartseiteEinloggenLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(ButtonStartseiteEinloggen)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        StartseiteEinloggenLayout.setVerticalGroup(
            StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartseiteEinloggenLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EinloggenBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StartseiteEinloggenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(EinloggenPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(ButtonStartseiteEinloggen)
                .addContainerGap(361, Short.MAX_VALUE))
        );

        getContentPane().add(StartseiteEinloggen, "card8");

        ButtonMenuProjektAnlegen.setText("Projekt anlegen");
        ButtonMenuProjektAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuProjektAnlegenActionPerformed(evt);
            }
        });

        ButtonMenuBenutzerAnlegen.setText("Benutzer anlegen");
        ButtonMenuBenutzerAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuBenutzerAnlegenActionPerformed(evt);
            }
        });

        ButtonMenuProjekteAnsehen.setText("Projekte ansehen");
        ButtonMenuProjekteAnsehen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuProjekteAnsehenActionPerformed(evt);
            }
        });

        ButtonMenuArbeitspaketeAnsehen.setText("Arbeitspakete ansehen");
        ButtonMenuArbeitspaketeAnsehen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuArbeitspaketeAnsehenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonMenuProjekteAnsehen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonMenuProjektAnlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonMenuBenutzerAnlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonMenuArbeitspaketeAnsehen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMenuProjektAnlegen)
                    .addComponent(ButtonMenuBenutzerAnlegen))
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMenuProjekteAnsehen)
                    .addComponent(ButtonMenuArbeitspaketeAnsehen))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        getContentPane().add(Menu, "card4");

        ProjektAnlegen.setPreferredSize(new java.awt.Dimension(700, 600));

        LabelName.setText("Name");

        LabelBeschreibung.setText("Beschreibung");

        LabelDeadline.setText("Deadline");

        ButtonProjektAnlegen.setText("Weiter");
        ButtonProjektAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProjektAnlegenActionPerformed(evt);
            }
        });

        TitelProjektAnlegen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitelProjektAnlegen.setText("Projekt Anlegen");

        ComboBoxTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxMonat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));

        ComboBoxJahr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        ButtonBackProjektAnlegen.setText("Zurück");
        ButtonBackProjektAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackProjektAnlegenActionPerformed(evt);
            }
        });

        TextAreaBeschreibung.setColumns(20);
        TextAreaBeschreibung.setLineWrap(true);
        TextAreaBeschreibung.setRows(5);
        TextAreaBeschreibung.setWrapStyleWord(true);
        jScrollPane8.setViewportView(TextAreaBeschreibung);

        javax.swing.GroupLayout ProjektAnlegenLayout = new javax.swing.GroupLayout(ProjektAnlegen);
        ProjektAnlegen.setLayout(ProjektAnlegenLayout);
        ProjektAnlegenLayout.setHorizontalGroup(
            ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitelProjektAnlegen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                        .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBeschreibung)
                            .addComponent(LabelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonProjektAnlegen)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonBackProjektAnlegen, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                                .addComponent(ComboBoxTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxMonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxJahr, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        ProjektAnlegenLayout.setVerticalGroup(
            ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitelProjektAnlegen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBackProjektAnlegen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDeadline)
                    .addComponent(ComboBoxTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxJahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelBeschreibung)
                    .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(ButtonProjektAnlegen)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(ProjektAnlegen, "card2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Arbeitspakete ansehen");

        ListArbeitspaketeAnsehen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(ListArbeitspaketeAnsehen);

        jLabel15.setText("Arbeitspakete:");

        jLabel16.setText("Beschreibung:");

        RadioButtonArbeitspaketFertig.setText("Fertig");

        ButtonArbeitspaketeAnsehenZurück.setText("Zurück");
        ButtonArbeitspaketeAnsehenZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArbeitspaketeAnsehenZurückActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ArbeitspaketeAnsehenLayout = new javax.swing.GroupLayout(ArbeitspaketeAnsehen);
        ArbeitspaketeAnsehen.setLayout(ArbeitspaketeAnsehenLayout);
        ArbeitspaketeAnsehenLayout.setHorizontalGroup(
            ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketeAnsehenLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArbeitspaketeAnsehenLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(RadioButtonArbeitspaketFertig))
                    .addComponent(jTextField1))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArbeitspaketeAnsehenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonArbeitspaketeAnsehenZurück)
                .addContainerGap())
        );
        ArbeitspaketeAnsehenLayout.setVerticalGroup(
            ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketeAnsehenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonArbeitspaketeAnsehenZurück)
                .addGap(5, 5, 5)
                .addComponent(jLabel14)
                .addGap(37, 37, 37)
                .addGroup(ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(RadioButtonArbeitspaketFertig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArbeitspaketeAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        getContentPane().add(ArbeitspaketeAnsehen, "card9");

        ProjekteAnsehen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProjekteAnsehenComponentShown(evt);
            }
        });

        ListProjekteAnsehen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListProjekteAnsehenComponentShown(evt);
            }
        });
        ListProjekteAnsehen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListProjekteAnsehenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListProjekteAnsehen);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Projekte Ansehen");

        ButtonBackProjekteAnsehen.setText("Zurück");
        ButtonBackProjekteAnsehen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackProjekteAnsehenActionPerformed(evt);
            }
        });

        ButtonProjektBearbeiten.setText("Bearbeiten");
        ButtonProjektBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProjektBearbeitenActionPerformed(evt);
            }
        });

        TextAreaProjektBeschreibung.setEditable(false);
        TextAreaProjektBeschreibung.setColumns(20);
        TextAreaProjektBeschreibung.setLineWrap(true);
        TextAreaProjektBeschreibung.setRows(5);
        TextAreaProjektBeschreibung.setWrapStyleWord(true);
        jScrollPane3.setViewportView(TextAreaProjektBeschreibung);

        javax.swing.GroupLayout ProjekteAnsehenLayout = new javax.swing.GroupLayout(ProjekteAnsehen);
        ProjekteAnsehen.setLayout(ProjekteAnsehenLayout);
        ProjekteAnsehenLayout.setHorizontalGroup(
            ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                        .addComponent(ButtonProjektBearbeiten)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                        .addGroup(ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonBackProjekteAnsehen)))
                        .addGap(21, 21, 21))))
        );
        ProjekteAnsehenLayout.setVerticalGroup(
            ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjekteAnsehenLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(ButtonBackProjekteAnsehen))
                .addGap(84, 84, 84)
                .addGroup(ProjekteAnsehenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(ButtonProjektBearbeiten)
                .addGap(42, 42, 42))
        );

        getContentPane().add(ProjekteAnsehen, "card6");

        LabelProjekteAnsehenSub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelProjekteAnsehenSub.setText("Projekt bearbeiten");

        LabelProjektName.setText("Name");

        LabelProjektBeschreibung.setText("Beschreibung");

        LabelProjektDeadline.setText("Deadline");

        LabelKommentar.setText("Kommentar");

        jLabel2.setText("Notiz");

        jLabel3.setText("Arbeitspakete");

        ButtonArbeitspaketBearbeiten.setText("Arbeitspaket ändern");
        ButtonArbeitspaketBearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArbeitspaketBearbeitenActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(ListArbeitspakete);

        ButtonProjektBearbeitenZurück.setText("Zurück");
        ButtonProjektBearbeitenZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProjektBearbeitenZurückActionPerformed(evt);
            }
        });

        ButtonProjektAendern.setText("Ändern");
        ButtonProjektAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProjektAendernActionPerformed(evt);
            }
        });

        ComboBoxProjektBearbeitenTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxProjektBearbeitenMonat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));

        ComboBoxProjektBearbeitenJahr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        javax.swing.GroupLayout ProjektBearbeitenLayout = new javax.swing.GroupLayout(ProjektBearbeiten);
        ProjektBearbeiten.setLayout(ProjektBearbeitenLayout);
        ProjektBearbeitenLayout.setHorizontalGroup(
            ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjektBearbeitenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LabelProjektName)
                    .addComponent(LabelProjektDeadline)
                    .addComponent(LabelProjekteAnsehenSub)
                    .addComponent(LabelProjektBeschreibung)
                    .addComponent(LabelKommentar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjektBearbeitenLayout.createSequentialGroup()
                        .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldNotiz, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(TextFieldProjektBeschreibung, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldProjektName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextFieldKommentar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjektBearbeitenLayout.createSequentialGroup()
                        .addComponent(ButtonProjektBearbeitenZurück)
                        .addGap(24, 24, 24))
                    .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                        .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonProjektAendern)
                            .addComponent(ButtonArbeitspaketBearbeiten)
                            .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                                        .addComponent(ComboBoxProjektBearbeitenTag, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxProjektBearbeitenMonat, 0, 1, Short.MAX_VALUE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxProjektBearbeitenJahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        ProjektBearbeitenLayout.setVerticalGroup(
            ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelProjekteAnsehenSub)
                    .addComponent(ButtonProjektBearbeitenZurück))
                .addGap(34, 34, 34)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                        .addComponent(LabelProjektName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelProjektBeschreibung)
                        .addGap(28, 28, 28)
                        .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelProjektDeadline)
                            .addComponent(ComboBoxProjektBearbeitenTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxProjektBearbeitenMonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxProjektBearbeitenJahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProjektBearbeitenLayout.createSequentialGroup()
                        .addComponent(TextFieldProjektName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(TextFieldProjektBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addGap(58, 58, 58)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKommentar)
                    .addComponent(TextFieldKommentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldNotiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(ProjektBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(ButtonArbeitspaketBearbeiten)
                .addGap(38, 38, 38)
                .addComponent(ButtonProjektAendern)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ProjektBearbeiten, "card7");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Arbeitspaket Anlegen");

        ButtonArbeitspaketAnlegenZurück.setText("Zurück");
        ButtonArbeitspaketAnlegenZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArbeitspaketAnlegenZurückActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Beschreibung");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Deadline");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Kommentar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Notiz");

        ButtonArbeitspaketAnlegen.setText("weiter");
        ButtonArbeitspaketAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArbeitspaketAnlegenActionPerformed(evt);
            }
        });

        ComboBoxATag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxAMonat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));

        ComboBoxAJahr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        TextAriaBeschreibung.setColumns(20);
        TextAriaBeschreibung.setLineWrap(true);
        TextAriaBeschreibung.setRows(5);
        jScrollPane7.setViewportView(TextAriaBeschreibung);

        javax.swing.GroupLayout ArbeitspaketAnlegenLayout = new javax.swing.GroupLayout(ArbeitspaketAnlegen);
        ArbeitspaketAnlegen.setLayout(ArbeitspaketAnlegenLayout);
        ArbeitspaketAnlegenLayout.setHorizontalGroup(
            ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonArbeitspaketAnlegenZurück)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArbeitspaketAnlegenLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldAName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                        .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                                    .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(122, 122, 122)
                                    .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonArbeitspaketAnlegen)
                                        .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                                            .addComponent(ComboBoxATag, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ComboBoxAMonat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ComboBoxAJahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        ArbeitspaketAnlegenLayout.setVerticalGroup(
            ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketAnlegenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(ButtonArbeitspaketAnlegenZurück))
                .addGap(35, 35, 35)
                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextFieldAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArbeitspaketAnlegenLayout.createSequentialGroup()
                        .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArbeitspaketAnlegenLayout.createSequentialGroup()
                                .addGroup(ArbeitspaketAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxATag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxAMonat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxAJahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(55, 55, 55)
                                .addComponent(jLabel9))
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10))
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ButtonArbeitspaketAnlegen)
                .addGap(143, 143, 143))
        );

        getContentPane().add(ArbeitspaketAnlegen, "card7");

        TitelBenutzerAnlegen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitelBenutzerAnlegen.setText("Benutzerprofil anlegen");

        LabelVorname.setText("Vorname");

        LabelNachname.setText("Nachname");

        LabelPasswort.setText("Passwort");

        LabelRang.setText("Rang");

        RadioButtonGroupRangAuswaehlen.add(RadioButtonStandardBenutzer);
        RadioButtonStandardBenutzer.setText("Standard Benutzer");

        RadioButtonGroupRangAuswaehlen.add(RadioButtonAdministrator);
        RadioButtonAdministrator.setText("Administrator");

        ButtonBenutzerAnlegen.setText("Anlegen");
        ButtonBenutzerAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBenutzerAnlegenActionPerformed(evt);
            }
        });

        ButtonBenutzerprofilAnlegenZurück.setText("Zurück");
        ButtonBenutzerprofilAnlegenZurück.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBenutzerprofilAnlegenZurückActionPerformed(evt);
            }
        });

        jLabel11.setText("Benutzername");

        javax.swing.GroupLayout BenutzerAnlegenLayout = new javax.swing.GroupLayout(BenutzerAnlegen);
        BenutzerAnlegen.setLayout(BenutzerAnlegenLayout);
        BenutzerAnlegenLayout.setHorizontalGroup(
            BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                        .addComponent(TitelBenutzerAnlegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonBenutzerprofilAnlegenZurück)
                        .addGap(25, 25, 25))
                    .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                        .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelVorname)
                            .addComponent(LabelNachname)
                            .addComponent(LabelPasswort)
                            .addComponent(LabelRang)
                            .addComponent(jLabel11))
                        .addGap(53, 53, 53)
                        .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RadioButtonAdministrator)
                            .addComponent(TextFieldVorname)
                            .addComponent(TextFieldNachname)
                            .addComponent(TextFieldPasswort)
                            .addComponent(RadioButtonStandardBenutzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonBenutzerAnlegen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldBenutzername))
                        .addContainerGap(171, Short.MAX_VALUE))))
        );
        BenutzerAnlegenLayout.setVerticalGroup(
            BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                        .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitelBenutzerAnlegen)
                            .addComponent(ButtonBenutzerprofilAnlegenZurück))
                        .addGap(38, 38, 38)
                        .addComponent(LabelVorname))
                    .addComponent(TextFieldVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNachname)
                    .addComponent(TextFieldNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(TextFieldBenutzername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPasswort)
                    .addComponent(TextFieldPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRang)
                    .addComponent(RadioButtonStandardBenutzer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonAdministrator)
                .addGap(40, 40, 40)
                .addComponent(ButtonBenutzerAnlegen)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        getContentPane().add(BenutzerAnlegen, "card3");

        jLabel8.setText("Mitarbeiter Hinzufügen");

        jScrollPane1.setViewportView(ListeMitarbeiterHinzufuegen);

        ButtonBackMenu.setText("Menü");
        ButtonBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackMenuActionPerformed(evt);
            }
        });

        ButtonWeiterArbeitspakete.setText("Weiteres Arbeitspaket");
        ButtonWeiterArbeitspakete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWeiterArbeitspaketeActionPerformed(evt);
            }
        });

        ButtonMitarbeiterHinzufügen.setText("Hinzufügen");
        ButtonMitarbeiterHinzufügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMitarbeiterHinzufügenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MitarbeiterHinzufuegenLayout = new javax.swing.GroupLayout(MitarbeiterHinzufuegen);
        MitarbeiterHinzufuegen.setLayout(MitarbeiterHinzufuegenLayout);
        MitarbeiterHinzufuegenLayout.setHorizontalGroup(
            MitarbeiterHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                .addGroup(MitarbeiterHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(MitarbeiterHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                                .addComponent(ButtonBackMenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonWeiterArbeitspakete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(ButtonMitarbeiterHinzufügen)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        MitarbeiterHinzufuegenLayout.setVerticalGroup(
            MitarbeiterHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MitarbeiterHinzufuegenLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ButtonMitarbeiterHinzufügen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(MitarbeiterHinzufuegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBackMenu)
                    .addComponent(ButtonWeiterArbeitspakete))
                .addGap(53, 53, 53))
        );

        getContentPane().add(MitarbeiterHinzufuegen, "card10");

        jLabel17.setText("Arbeitspaket bearbeiten");

        jLabel18.setText("Name");

        TextAreaABeschreibungBearbeiten.setColumns(20);
        TextAreaABeschreibungBearbeiten.setRows(5);
        jScrollPane5.setViewportView(TextAreaABeschreibungBearbeiten);

        jLabel19.setText("Beschreibung");

        ComboBoxATagBearbeiten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        ComboBoxAMonatBearbeiten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));

        ComboBoxAJahrBearbeiten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLabel20.setText("Deadline");

        CheckBoxArbeitspaketFertig.setText("Fertig");

        ButtonArbeitspaketBearbeitenÄndern.setText("Ändern");

        javax.swing.GroupLayout ArbeitspaketBearbeitenLayout = new javax.swing.GroupLayout(ArbeitspaketBearbeiten);
        ArbeitspaketBearbeiten.setLayout(ArbeitspaketBearbeitenLayout);
        ArbeitspaketBearbeitenLayout.setHorizontalGroup(
            ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketBearbeitenLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArbeitspaketBearbeitenLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArbeitspaketBearbeitenLayout.createSequentialGroup()
                        .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxArbeitspaketFertig)
                            .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(ArbeitspaketBearbeitenLayout.createSequentialGroup()
                                    .addComponent(ComboBoxATagBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxAMonatBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ComboBoxAJahrBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane5)
                                .addComponent(TextFieldANameBearbeiten))
                            .addComponent(ButtonArbeitspaketBearbeitenÄndern))
                        .addGap(48, 48, 48))))
        );
        ArbeitspaketBearbeitenLayout.setVerticalGroup(
            ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArbeitspaketBearbeitenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(52, 52, 52)
                .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldANameBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(32, 32, 32)
                .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(34, 34, 34)
                .addGroup(ArbeitspaketBearbeitenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxATagBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAMonatBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxAJahrBearbeiten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(57, 57, 57)
                .addComponent(CheckBoxArbeitspaketFertig)
                .addGap(52, 52, 52)
                .addComponent(ButtonArbeitspaketBearbeitenÄndern)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        getContentPane().add(ArbeitspaketBearbeiten, "card11");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ButtonMenuProjektAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuProjektAnlegenActionPerformed
    Menu.setVisible(false); 
    ProjektAnlegen.setVisible(true);
    
    
   
    }//GEN-LAST:event_ButtonMenuProjektAnlegenActionPerformed

    
    private void ButtonMenuBenutzerAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuBenutzerAnlegenActionPerformed
       Menu.setVisible(false);
       BenutzerAnlegen.setVisible(true);
    }//GEN-LAST:event_ButtonMenuBenutzerAnlegenActionPerformed

    
    private void ButtonBenutzerAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBenutzerAnlegenActionPerformed
       String rang = new String();
       
       if(RadioButtonGroupRangAuswaehlen.getSelection().equals(RadioButtonStandardBenutzer.getModel()) )rang = "Standard Benutzer";
       if(RadioButtonGroupRangAuswaehlen.getSelection().equals(RadioButtonAdministrator.getModel()) )rang = "Administrator";
       
             
       bv.erstelleProfil(TextFieldNachname.getText(), TextFieldVorname.getText(), TextFieldPasswort.getText(), rang, TextFieldBenutzername.getText());
       
       BenutzerAnlegen.setVisible(false);
       Menu.setVisible(true);
    }//GEN-LAST:event_ButtonBenutzerAnlegenActionPerformed

    private void ProjekteAnsehenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProjekteAnsehenComponentShown
       ListProjekteAnsehen.removeAll();
        List<Projekt> liste = pv.getProjekte();
        //List<Arbeitspaket> a_liste = av.getArbeitspaket();
     
        DefaultListModel ListModel = new DefaultListModel();
       ListProjekteAnsehen.setModel(ListModel);
        for(int i = 0; i < liste.size(); i++){ 
            ListModel.addElement(liste.get(i).getname() ); 
            // for(int j = 0; j < a_liste.size(); j++){
              //   ListModel.addElement("   " + a_liste.get(j).getName()); 
             //}
        } 
      
        
    }//GEN-LAST:event_ProjekteAnsehenComponentShown

    
    
    
    private void ButtonMenuProjekteAnsehenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuProjekteAnsehenActionPerformed
        Menu.setVisible(false);
        ProjekteAnsehen.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ButtonMenuProjekteAnsehenActionPerformed

    private void ButtonBackProjekteAnsehenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackProjekteAnsehenActionPerformed
       ProjekteAnsehen.setVisible(false);
        Menu.setVisible(true);
    }//GEN-LAST:event_ButtonBackProjekteAnsehenActionPerformed

    private void ListProjekteAnsehenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListProjekteAnsehenValueChanged
        List<Projekt> projekte = pv.getProjekte();
       
        
        if (!evt.getValueIsAdjusting() ) {
            int selectedindex = ListProjekteAnsehen.getSelectedIndex();
            if(selectedindex >= 0){
                  TextAreaProjektBeschreibung.setText("Beschreibung: " + projekte.get(selectedindex).getbeschreibung() + "\n");
                  int tag = projekte.get(selectedindex).getDeadline().get(Calendar.DAY_OF_MONTH);
                  int monat = projekte.get(selectedindex).getDeadline().get(Calendar.MONTH)+1;
                  int jahr = projekte.get(selectedindex).getDeadline().get(Calendar.YEAR);
                  String date = tag + "." + monat + "." + jahr;
                  
                  TextAreaProjektBeschreibung.append("\n" + "Deadline: " + date + "\n" );
            }
        }
    }//GEN-LAST:event_ListProjekteAnsehenValueChanged

    private void ListProjekteAnsehenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListProjekteAnsehenComponentShown

    }//GEN-LAST:event_ListProjekteAnsehenComponentShown

    private void ButtonProjektBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProjektBearbeitenActionPerformed
      List<Projekt> projekte = pv.getProjekte();
      Projekt projekt = projekte.get(ListProjekteAnsehen.getSelectedIndex());
      List<Arbeitspaket> a = av.getArbeitspaket(projekt);
        
      ProjekteAnsehen.setVisible(false);
      ProjektBearbeiten.setVisible(true);
     
      TextFieldProjektName.setText(projekte.get(ListProjekteAnsehen.getSelectedIndex()).getname());
      TextFieldProjektBeschreibung.setText(projekte.get(ListProjekteAnsehen.getSelectedIndex()).getbeschreibung());
      ComboBoxProjektBearbeitenTag.setSelectedIndex(projekte.get(ListProjekteAnsehen.getSelectedIndex()).getDeadline().get(Calendar.DAY_OF_MONTH)-1);
      ComboBoxProjektBearbeitenMonat.setSelectedIndex(projekte.get(ListProjekteAnsehen.getSelectedIndex()).getDeadline().get(Calendar.MONTH));
      ComboBoxProjektBearbeitenJahr.setSelectedItem(projekte.get(ListProjekteAnsehen.getSelectedIndex()).getDeadline().get(Calendar.YEAR));
    
      DefaultListModel dm = new DefaultListModel();
      ListArbeitspakete.setModel(dm);
      //
      for(int i = 0 ; i < a.size(); i++){
          dm.addElement(a.get(i).getName());
      }
      
   
    }//GEN-LAST:event_ButtonProjektBearbeitenActionPerformed

    private void ButtonBenutzerprofilAnlegenZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBenutzerprofilAnlegenZurückActionPerformed
        BenutzerAnlegen.setVisible(false);
        Menu.setVisible(true);
    }//GEN-LAST:event_ButtonBenutzerprofilAnlegenZurückActionPerformed

    private void ButtonArbeitspaketBearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArbeitspaketBearbeitenActionPerformed
       List<Projekt> projekte = pv.getProjekte();
       Projekt projekt = projekte.get(ListProjekteAnsehen.getSelectedIndex());  
       List<Arbeitspaket> a = av.getArbeitspaket(projekt);
       Arbeitspaket ap = a.get(ListArbeitspakete.getSelectedIndex());
        
       TextFieldANameBearbeiten.setText(ap.getName());
       TextAreaABeschreibungBearbeiten.setText(ap.getBeschreibung());
       ComboBoxATag.setSelectedIndex(ap.getDeadline().get(Calendar.DAY_OF_MONTH)-1);
       ComboBoxAMonat.setSelectedIndex(ap.getDeadline().get(Calendar.MONTH));
       ComboBoxAJahr.setSelectedItem(ap.getDeadline().get(Calendar.YEAR));
       
        ProjektBearbeiten.setVisible(false);
        ArbeitspaketBearbeiten.setVisible(true);
        
        
        
       
    }//GEN-LAST:event_ButtonArbeitspaketBearbeitenActionPerformed

    private void ButtonArbeitspaketAnlegenZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArbeitspaketAnlegenZurückActionPerformed
        ArbeitspaketAnlegen.setVisible(false);
        ProjektBearbeiten.setVisible(true);
    }//GEN-LAST:event_ButtonArbeitspaketAnlegenZurückActionPerformed

    private void ButtonProjektBearbeitenZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProjektBearbeitenZurückActionPerformed
       ProjektBearbeiten.setVisible(false);
       ProjekteAnsehen.setVisible(true);
    }//GEN-LAST:event_ButtonProjektBearbeitenZurückActionPerformed

    private void ButtonArbeitspaketAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArbeitspaketAnlegenActionPerformed
        int tag = Integer.parseInt((String)ComboBoxATag.getSelectedItem());
        int monat = ComboBoxAMonat.getSelectedIndex()+1;
        int jahr = Integer.parseInt((String)ComboBoxAJahr.getSelectedItem());
        
        List<Projekt> p = pv.getProjekte();
        List<Mitarbeiter> m = bv.getMitarbeiter();
        //List<Arbeitspaket> a = av.getArbeitspaket();
        
        Projekt projekt = p.get(p.size()-1);
        
            av.anlegeArbeitspaket(TextFieldAName.getText(),false, TextAriaBeschreibung.getText(), tag, monat, jahr, projekt);  
       
       
        TextFieldAName.setText("");
        TextAriaBeschreibung.setText("");
        ComboBoxATag.setSelectedIndex(0);
        ComboBoxAMonat.setSelectedIndex(0);
        ComboBoxAJahr.setSelectedIndex(0);
        
         DefaultListModel dm = new DefaultListModel();
       
        ListeMitarbeiterHinzufuegen.setModel(dm);
        
        
        for(int i = 0; i < m.size(); i++){ 
            
            dm.addElement(m.get(i).getName() + ", " + m.get(i).getVorname() );
        }
        
        
        ArbeitspaketAnlegen.setVisible(false);
        MitarbeiterHinzufuegen.setVisible(true);
    }//GEN-LAST:event_ButtonArbeitspaketAnlegenActionPerformed

    private void ButtonProjektAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProjektAendernActionPerformed
        List<Projekt> p = pv.getProjekte();        
        Projekt projekt = p.get(ListProjekteAnsehen.getSelectedIndex());
        
        projekt.setName(TextFieldProjektName.getText());
        projekt.setBeschreibung(TextFieldProjektBeschreibung.getText());
       
        
        int tag = Integer.parseInt((String)ComboBoxProjektBearbeitenTag.getSelectedItem());
        int monat = ComboBoxProjektBearbeitenMonat.getSelectedIndex()+1;
        int jahr = Integer.parseInt((String)ComboBoxProjektBearbeitenJahr.getSelectedItem());
        String date = tag+ "." + monat + "." + jahr;
        System.out.println(date);
        pv.bearbeiteDeadline(projekt, tag, monat, jahr); 
      TextAreaProjektBeschreibung.setText("Beschreibung: " + projekt.getbeschreibung() + "\n" + "\n" + "Deadline: " + date + "\n" );
      
      
    }//GEN-LAST:event_ButtonProjektAendernActionPerformed

    private void ButtonStartseiteEinloggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartseiteEinloggenActionPerformed
       StartseiteEinloggen.setVisible(false);
       Menu.setVisible(true);
    }//GEN-LAST:event_ButtonStartseiteEinloggenActionPerformed

    private void ButtonMenuArbeitspaketeAnsehenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuArbeitspaketeAnsehenActionPerformed
       Menu.setVisible(false);
       ArbeitspaketeAnsehen.setVisible(true);
    }//GEN-LAST:event_ButtonMenuArbeitspaketeAnsehenActionPerformed

    private void ButtonArbeitspaketeAnsehenZurückActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArbeitspaketeAnsehenZurückActionPerformed
        ArbeitspaketeAnsehen.setVisible(false);
        Menu.setVisible(true);
    }//GEN-LAST:event_ButtonArbeitspaketeAnsehenZurückActionPerformed

    private void ButtonWeiterArbeitspaketeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWeiterArbeitspaketeActionPerformed
        MitarbeiterHinzufuegen.setVisible(false);
        ArbeitspaketAnlegen.setVisible(true);
        
        
    }//GEN-LAST:event_ButtonWeiterArbeitspaketeActionPerformed

    private void ButtonBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackMenuActionPerformed
       MitarbeiterHinzufuegen.setVisible(false);
       Menu.setVisible(true);
    }//GEN-LAST:event_ButtonBackMenuActionPerformed

    private void ButtonMitarbeiterHinzufügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMitarbeiterHinzufügenActionPerformed
     List<Projekt> p = pv.getProjekte();
     List<Mitarbeiter> m = bv.getMitarbeiter();
     Projekt projekt = p.get(p.size()-1);
     List<Arbeitspaket> ap = av.getArbeitspaket(projekt);
      
     Mitarbeiter mitarbeiter = m.get(ListeMitarbeiterHinzufuegen.getSelectedIndex());
     
     av.weiseMitarbeiterZu(ap.get(ap.size() - 1), mitarbeiter);
    }//GEN-LAST:event_ButtonMitarbeiterHinzufügenActionPerformed

    private void ButtonBackProjektAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackProjektAnlegenActionPerformed
        ProjektAnlegen.setVisible(false);
        Menu.setVisible(true);
    }//GEN-LAST:event_ButtonBackProjektAnlegenActionPerformed

    private void ButtonProjektAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProjektAnlegenActionPerformed
        ProjektAnlegen.setVisible(false);
        ArbeitspaketAnlegen.setVisible(true);
    }//GEN-LAST:event_ButtonProjektAnlegenActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ArbeitspaketAnlegen;
    private javax.swing.JPanel ArbeitspaketBearbeiten;
    private javax.swing.JPanel ArbeitspaketeAnsehen;
    private javax.swing.JPanel BenutzerAnlegen;
    private javax.swing.JButton ButtonArbeitspaketAnlegen;
    private javax.swing.JButton ButtonArbeitspaketAnlegenZurück;
    private javax.swing.JButton ButtonArbeitspaketBearbeiten;
    private javax.swing.JButton ButtonArbeitspaketBearbeitenÄndern;
    private javax.swing.JButton ButtonArbeitspaketeAnsehenZurück;
    private javax.swing.JButton ButtonBackMenu;
    private javax.swing.JButton ButtonBackProjektAnlegen;
    private javax.swing.JButton ButtonBackProjekteAnsehen;
    private javax.swing.JButton ButtonBenutzerAnlegen;
    private javax.swing.JButton ButtonBenutzerprofilAnlegenZurück;
    private javax.swing.JButton ButtonMenuArbeitspaketeAnsehen;
    private javax.swing.JButton ButtonMenuBenutzerAnlegen;
    private javax.swing.JButton ButtonMenuProjektAnlegen;
    private javax.swing.JButton ButtonMenuProjekteAnsehen;
    private javax.swing.JButton ButtonMitarbeiterHinzufügen;
    private javax.swing.JButton ButtonProjektAendern;
    private javax.swing.JButton ButtonProjektAnlegen;
    private javax.swing.JButton ButtonProjektBearbeiten;
    private javax.swing.JButton ButtonProjektBearbeitenZurück;
    private javax.swing.JButton ButtonStartseiteEinloggen;
    private javax.swing.JButton ButtonWeiterArbeitspakete;
    private javax.swing.JCheckBox CheckBoxArbeitspaketFertig;
    private javax.swing.JComboBox<String> ComboBoxAJahr;
    private javax.swing.JComboBox<String> ComboBoxAJahrBearbeiten;
    private javax.swing.JComboBox<String> ComboBoxAMonat;
    private javax.swing.JComboBox<String> ComboBoxAMonatBearbeiten;
    private javax.swing.JComboBox<String> ComboBoxATag;
    private javax.swing.JComboBox<String> ComboBoxATagBearbeiten;
    private javax.swing.JComboBox<String> ComboBoxJahr;
    private javax.swing.JComboBox<String> ComboBoxMonat;
    private javax.swing.JComboBox<String> ComboBoxProjektBearbeitenJahr;
    private javax.swing.JComboBox<String> ComboBoxProjektBearbeitenMonat;
    private javax.swing.JComboBox<String> ComboBoxProjektBearbeitenTag;
    private javax.swing.JComboBox<String> ComboBoxTag;
    private javax.swing.JTextField EinloggenBenutzername;
    private javax.swing.JPasswordField EinloggenPasswort;
    private javax.swing.JLabel LabelBeschreibung;
    private javax.swing.JLabel LabelDeadline;
    private javax.swing.JLabel LabelKommentar;
    private javax.swing.JLabel LabelNachname;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPasswort;
    private javax.swing.JLabel LabelProjektBeschreibung;
    private javax.swing.JLabel LabelProjektDeadline;
    private javax.swing.JLabel LabelProjektName;
    private javax.swing.JLabel LabelProjekteAnsehenSub;
    private javax.swing.JLabel LabelRang;
    private javax.swing.JLabel LabelVorname;
    private javax.swing.JList<String> ListArbeitspakete;
    private javax.swing.JList<String> ListArbeitspaketeAnsehen;
    private javax.swing.JList<String> ListProjekteAnsehen;
    private javax.swing.JList<String> ListeMitarbeiterHinzufuegen;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MitarbeiterHinzufuegen;
    private javax.swing.JPanel ProjektAnlegen;
    private javax.swing.JPanel ProjektBearbeiten;
    private javax.swing.JPanel ProjekteAnsehen;
    private javax.swing.JRadioButton RadioButtonAdministrator;
    private javax.swing.JRadioButton RadioButtonArbeitspaketFertig;
    private javax.swing.ButtonGroup RadioButtonGroupRangAuswaehlen;
    private javax.swing.JRadioButton RadioButtonStandardBenutzer;
    private javax.swing.JPanel StartseiteEinloggen;
    private javax.swing.JTextArea TextAreaABeschreibungBearbeiten;
    private javax.swing.JTextArea TextAreaBeschreibung;
    private javax.swing.JTextArea TextAreaProjektBeschreibung;
    private javax.swing.JTextArea TextAriaBeschreibung;
    private javax.swing.JTextField TextFieldAName;
    private javax.swing.JTextField TextFieldANameBearbeiten;
    private javax.swing.JTextField TextFieldBenutzername;
    private javax.swing.JTextField TextFieldKommentar;
    private javax.swing.JTextField TextFieldNachname;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldNotiz;
    private javax.swing.JTextField TextFieldPasswort;
    private javax.swing.JTextField TextFieldProjektBeschreibung;
    private javax.swing.JTextField TextFieldProjektName;
    private javax.swing.JTextField TextFieldVorname;
    private javax.swing.JLabel TitelBenutzerAnlegen;
    private javax.swing.JLabel TitelProjektAnlegen;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
