/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jan Beuster
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
        
    }
ProjektVerwaltung pv = new ProjektVerwaltung();
BenutzerVerwaltung bv = new BenutzerVerwaltung();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButtonGroupRangAuswaehlen = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPanel();
        ButtonMenuProjektAnlegen = new javax.swing.JButton();
        ButtonMenuBenutzerAnlegen = new javax.swing.JButton();
        ProjektAnlegen = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        LabelBeschreibung = new javax.swing.JLabel();
        LabelDeadline = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        TextFieldBeschreibung = new javax.swing.JTextField();
        TextFieldDeadline = new javax.swing.JTextField();
        ButtonProjektAnlegen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeMitarbeiterHinzufügen = new javax.swing.JList<>();
        ButtonMitarbeiterHinzufügen = new javax.swing.JButton();
        LabelMitarbeiter = new javax.swing.JLabel();
        TitelProjektAnlegen = new javax.swing.JLabel();
        BenutzerAnlegen = new javax.swing.JPanel();
        TitelBenutzerAnlegen = new javax.swing.JLabel();
        LabelVorname = new javax.swing.JLabel();
        LabelNachname = new javax.swing.JLabel();
        LabelPasswort = new javax.swing.JLabel();
        LabelRang = new javax.swing.JLabel();
        TextFieldVorname = new javax.swing.JTextField();
        TextFieldNachname = new javax.swing.JTextField();
        TextFieldPasswort = new javax.swing.JTextField();
        RadioButtonStandardBenutzer = new javax.swing.JRadioButton();
        RadioButtonAdministrator = new javax.swing.JRadioButton();
        ButtonBenutzerAnlegen = new javax.swing.JButton();
        ProfilVerwalten = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        ButtonMenuProjektAnlegen.setText("Projekt anlegen");
        ButtonMenuProjektAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuProjektAnlegenActionPerformed(evt);
            }
        });

        ButtonMenuBenutzerAnlegen.setText("Benutzer anlegen");
        ButtonMenuBenutzerAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuBenutzerAnlegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ButtonMenuProjektAnlegen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ButtonMenuBenutzerAnlegen)
                .addGap(68, 68, 68))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMenuProjektAnlegen)
                    .addComponent(ButtonMenuBenutzerAnlegen))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        getContentPane().add(Menu, "card4");

        LabelName.setText("Name");

        LabelBeschreibung.setText("Beschreibung");

        LabelDeadline.setText("Deadline");

        ButtonProjektAnlegen.setText("Anlegen");
        ButtonProjektAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProjektAnlegenActionPerformed(evt);
            }
        });

        ListeMitarbeiterHinzufügen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListeMitarbeiterHinzufügen);

        ButtonMitarbeiterHinzufügen.setText("Hinzufügen");

        LabelMitarbeiter.setText("Mitarbeiter");

        TitelProjektAnlegen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitelProjektAnlegen.setText("Projekt Anlegen");

        javax.swing.GroupLayout ProjektAnlegenLayout = new javax.swing.GroupLayout(ProjektAnlegen);
        ProjektAnlegen.setLayout(ProjektAnlegenLayout);
        ProjektAnlegenLayout.setHorizontalGroup(
            ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitelProjektAnlegen)
                    .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                        .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelName)
                            .addComponent(LabelBeschreibung)
                            .addComponent(LabelDeadline)
                            .addComponent(LabelMitarbeiter))
                        .addGap(57, 57, 57)
                        .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonMitarbeiterHinzufügen, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TextFieldName)
                            .addComponent(TextFieldBeschreibung)
                            .addComponent(TextFieldDeadline)
                            .addComponent(jScrollPane1)
                            .addComponent(ButtonProjektAnlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        ProjektAnlegenLayout.setVerticalGroup(
            ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektAnlegenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitelProjektAnlegen)
                .addGap(33, 33, 33)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBeschreibung)
                    .addComponent(TextFieldBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDeadline)
                    .addComponent(TextFieldDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ProjektAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelMitarbeiter))
                .addGap(18, 18, 18)
                .addComponent(ButtonMitarbeiterHinzufügen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ButtonProjektAnlegen)
                .addGap(22, 22, 22))
        );

        getContentPane().add(ProjektAnlegen, "card2");

        TitelBenutzerAnlegen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitelBenutzerAnlegen.setText("Benutzerprofil anlegen");

        LabelVorname.setText("Vorname");

        LabelNachname.setText("Nachname");

        LabelPasswort.setText("Passwort");

        LabelRang.setText("Rang");

        RadioButtonGroupRangAuswaehlen.add(RadioButtonStandardBenutzer);
        RadioButtonStandardBenutzer.setText("Standard Benutzer");

        RadioButtonGroupRangAuswaehlen.add(RadioButtonAdministrator);
        RadioButtonAdministrator.setText("Administrator");

        ButtonBenutzerAnlegen.setText("Anlegen");
        ButtonBenutzerAnlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBenutzerAnlegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BenutzerAnlegenLayout = new javax.swing.GroupLayout(BenutzerAnlegen);
        BenutzerAnlegen.setLayout(BenutzerAnlegenLayout);
        BenutzerAnlegenLayout.setHorizontalGroup(
            BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitelBenutzerAnlegen)
                    .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                        .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelVorname)
                            .addComponent(LabelNachname)
                            .addComponent(LabelPasswort)
                            .addComponent(LabelRang))
                        .addGap(79, 79, 79)
                        .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonAdministrator)
                            .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextFieldVorname)
                                .addComponent(TextFieldNachname)
                                .addComponent(TextFieldPasswort, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(RadioButtonStandardBenutzer))
                            .addComponent(ButtonBenutzerAnlegen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        BenutzerAnlegenLayout.setVerticalGroup(
            BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BenutzerAnlegenLayout.createSequentialGroup()
                        .addComponent(TitelBenutzerAnlegen)
                        .addGap(43, 43, 43)
                        .addComponent(LabelVorname))
                    .addComponent(TextFieldVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNachname)
                    .addComponent(TextFieldNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPasswort)
                    .addComponent(TextFieldPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(BenutzerAnlegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRang)
                    .addComponent(RadioButtonStandardBenutzer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonAdministrator)
                .addGap(40, 40, 40)
                .addComponent(ButtonBenutzerAnlegen)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        getContentPane().add(BenutzerAnlegen, "card3");

        javax.swing.GroupLayout ProfilVerwaltenLayout = new javax.swing.GroupLayout(ProfilVerwalten);
        ProfilVerwalten.setLayout(ProfilVerwaltenLayout);
        ProfilVerwaltenLayout.setHorizontalGroup(
            ProfilVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ProfilVerwaltenLayout.setVerticalGroup(
            ProfilVerwaltenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        getContentPane().add(ProfilVerwalten, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonProjektAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProjektAnlegenActionPerformed
       pv.anlegenProjekt(TextFieldName.getText(), TextFieldBeschreibung.getText(), TextFieldDeadline.getText());  
    }//GEN-LAST:event_ButtonProjektAnlegenActionPerformed

    
    private void ButtonMenuProjektAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuProjektAnlegenActionPerformed
    Menu.setVisible(false); 
    ProjektAnlegen.setVisible(true);
   
    }//GEN-LAST:event_ButtonMenuProjektAnlegenActionPerformed

    
    private void ButtonMenuBenutzerAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuBenutzerAnlegenActionPerformed
       Menu.setVisible(false);
       BenutzerAnlegen.setVisible(true);
    }//GEN-LAST:event_ButtonMenuBenutzerAnlegenActionPerformed

    
    private void ButtonBenutzerAnlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBenutzerAnlegenActionPerformed
       String rang = new String();
       
       if(RadioButtonGroupRangAuswaehlen.getSelection().equals(RadioButtonStandardBenutzer.getModel()) )rang = "Standard Benutzer";
       if(RadioButtonGroupRangAuswaehlen.getSelection().equals(RadioButtonAdministrator.getModel()) )rang = "Administrator";
             
       bv.erstelleProfil(TextFieldNachname.getText(), TextFieldVorname.getText(), TextFieldPasswort.getText(), rang);
    }//GEN-LAST:event_ButtonBenutzerAnlegenActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BenutzerAnlegen;
    private javax.swing.JButton ButtonBenutzerAnlegen;
    private javax.swing.JButton ButtonMenuBenutzerAnlegen;
    private javax.swing.JButton ButtonMenuProjektAnlegen;
    private javax.swing.JButton ButtonMitarbeiterHinzufügen;
    private javax.swing.JButton ButtonProjektAnlegen;
    private javax.swing.JLabel LabelBeschreibung;
    private javax.swing.JLabel LabelDeadline;
    private javax.swing.JLabel LabelMitarbeiter;
    private javax.swing.JLabel LabelNachname;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPasswort;
    private javax.swing.JLabel LabelRang;
    private javax.swing.JLabel LabelVorname;
    private javax.swing.JList<String> ListeMitarbeiterHinzufügen;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel ProfilVerwalten;
    private javax.swing.JPanel ProjektAnlegen;
    private javax.swing.JRadioButton RadioButtonAdministrator;
    private javax.swing.ButtonGroup RadioButtonGroupRangAuswaehlen;
    private javax.swing.JRadioButton RadioButtonStandardBenutzer;
    private javax.swing.JTextField TextFieldBeschreibung;
    private javax.swing.JTextField TextFieldDeadline;
    private javax.swing.JTextField TextFieldNachname;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldPasswort;
    private javax.swing.JTextField TextFieldVorname;
    private javax.swing.JLabel TitelBenutzerAnlegen;
    private javax.swing.JLabel TitelProjektAnlegen;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
